services:
  - type: web
    name: pacmac-web
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: pacmac-db
          property: connectionString
    healthCheckPath: /health